create table b_kkqp_jgcl
(
  jlbh   VARCHAR2(32) not null,
  hphm   NVARCHAR2(16),
  hpzl   NUMBER(2),
  jgsj   DATE,
  clsd   NUMBER(4),
  zgxs   NUMBER(4),
  zdxs   NUMBER(4),
  cwkc   NUMBER(5,2),
  hpys   VARCHAR2(2),
  cllx   VARCHAR2(4),
  jllx   VARCHAR2(4),
  hdsj   NUMBER(8),
  bzwzdm VARCHAR2(16) not null,
  sbbh   VARCHAR2(32),
  cdbh   NUMBER(6),
  fxbh   VARCHAR2(4),
  tpsl   NUMBER(2),
  clbj   VARCHAR2(2),
  shbj   VARCHAR2(2) default 0,
  zfbj   VARCHAR2(2),
  sjly   VARCHAR2(20),
  cclx   NUMBER(2),
  bz     VARCHAR2(512),
  tjbj   VARCHAR2(2),
  csys   NUMBER(2),
  jllb   NUMBER(2),
  xsfx   NUMBER(2),
  csbj   NUMBER(2),
  yzys   NUMBER,
  tplx   NUMBER(6),
  xrsj   DATE default sysdate,
  url    VARCHAR2(512)
)
